<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Главная',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'info@adobemuse.ru',
		'to' => 'info@adobemuse.ru'
	),
	'fields' => array(
		'custom_U12328' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Name\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Email\' не может быть пустым.',
				'format' => 'Поле \'Email\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U12338' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Message',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Message\' не может быть пустым.'
			)
		),
		'custom_U12305' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'Выбрать модель',
			'required' => true,
			'optionItems' => array(
				'Mercedes-Benz SH bike black',
				'LAND ROVER Challenge G4 black',
				'BMW Super Bike black',
				'Mercedes-Benz SH bike white',
				'LAND ROVER Challenge G4 white',
				'BMW Super Bike white'
			),
			'errors' => array(
				'required' => 'Поле \'Выбрать модель\' не может быть пустым.',
				'format' => 'Недопустимое значение поля \"Выбрать модель\".'
			)
		)
	)
);

process_form($form);
?>
